// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyByvHWfUEIGOMboeIpGxhiNbPmu_21MWmw',
  //   appId: '1:568059105449:web:a00f2efd730d3709b159b8',
  //   messagingSenderId: '568059105449',
  //   projectId: 'galleria-25128',
  //   authDomain: 'galleria-25128.firebaseapp.com',
  //   storageBucket: 'galleria-25128.firebasestorage.app',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1b4R92_8QZSwIDArLvHG8iBaThuXw0A',
    appId: '1:568059105449:android:f1112da41cb0cd74b159b8',
    messagingSenderId: '568059105449',
    projectId: 'galleria-25128',
    storageBucket: 'galleria-25128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMy90L1JQQyl1WtcPfL0k7XP0wQrg5X54',
    appId: '1:568059105449:ios:ad87940a704416a3b159b8',
    messagingSenderId: '568059105449',
    projectId: 'galleria-25128',
    storageBucket: 'galleria-25128.firebasestorage.app',
    iosBundleId: 'com.example.galleria',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDMy90L1JQQyl1WtcPfL0k7XP0wQrg5X54',
  //   appId: '1:568059105449:ios:ad87940a704416a3b159b8',
  //   messagingSenderId: '568059105449',
  //   projectId: 'galleria-25128',
  //   storageBucket: 'galleria-25128.firebasestorage.app',
  //   iosBundleId: 'com.example.galleria',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyByvHWfUEIGOMboeIpGxhiNbPmu_21MWmw',
  //   appId: '1:568059105449:web:e4425db940147dc4b159b8',
  //   messagingSenderId: '568059105449',
  //   projectId: 'galleria-25128',
  //   authDomain: 'galleria-25128.firebaseapp.com',
  //   storageBucket: 'galleria-25128.firebasestorage.app',
  // );
}
